source 'https://rubygems.org'

ruby '2.1.1'

gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'spring'
  gem 'pry-rails'
  gem 'dotenv'
end

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails', '~> 3.0.0'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

gem 'ace-rails-ap'
gem 'modernizr-rails'
gem 'foundation-rails'
gem 'docker-api', require: 'docker'
gem 'puma'
