themes:
  textmate: 'Textmate'
  monokai: 'Monokai'
  tomorrow_night: 'Tomorrow Night'
  github: 'GitHub'
 
indents:
  2: '2 spaces'
  4: '4 spaces'
  8: '8 spaces'
  tab: 'Tabs'
 
languages:
  ruby: 'Ruby'
  golang: 'Go'
