#!/usr/bin/env rake
$LOAD_PATH.unshift File.expand_path("../lib", __FILE__)

require 'rspec/core/rake_task'
require 'exec-code/version'

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

task :build do
  system "gem build exec-code.gemspec"
end
 
task :release => :build do
  system "gem push exec-code-#{ExecCode::VERSION}"
end
