themes:
  tomorrow_night: 'Tomorrow Night'
  textmate: 'Textmate'
  monokai: 'Monokai'
  github: 'GitHub'

indents:
  '2': '2 spaces'
  '4': '4 spaces'
  '8': '8 spaces'
  tab: 'Tabs'

languages:
  ruby: 'Ruby'
  golang: 'Go'
  python2: 'Python 2'
  python3: 'Python 3'
  c: 'C'
  cpp: 'C++'
  csharp: 'C#'

keyboards:
  ace: 'Ace'
  vim: 'Vim'
  emacs: 'Emacs'
